#!/usr/bin/env python3
"""
process data generated by PageBuilder
"""

import json

INFN    = "document.json"
OUTFN   = "_DATA.json"



print ("PROCESSING ===========================================================")

########################################################################
## READING THE INPUT FILE
print ("reading", INFN)
with open(INFN, "r") as f: _json = f.read()
document_data = json.loads(_json)

#print ("analysing {} ({} records)".format(INFN, len(document_data)))
#refs = document_analysis['references']
refs = []

select = {}

for d in document_data:

    refs = d['_analysis']['references']
    TEMPLATE = "[{0[0]}] {0[1]} <a href='{0[1]}'>go</a>"
    TEMPLATE = "<li>{}</li>".format(TEMPLATE)
    ref_html = "\n".join(
        TEMPLATE.format(r)
        for r in refs
    )
    #ref_html = "<ul>\n{}\n</ul>\n".format(ref_html)
    print("FILENAME", d['_filename'], len(refs))
    #print("REFERENCES", ref_html)
    select[d['_filename']] = {"refs": ref_html}
#print(ref_html)


########################################################################
## WRITING THE OUTPUT FILE
out = {
    "_select": select,
}
with open(OUTFN, "w") as f: f.write(json.dumps(out))
#print("OUT:", out)


print ("END PROCESSING =======================================================")
